In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
ds = pd.read_csv("online_shoppers_intention.csv")

In [22]:
ds.isnull().values.any()

False

In [23]:
ds.head(10)

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   
5               0                      0.0              0   
6               0                      0.0              0   
7               1                      0.0              0   
8               0                      0.0              0   
9               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   
5                     0.0              19               154.216667   
6                     0.0               1                 0.000000   
7                     0.0               0                 0.000000   
8                     0.0               2                37.000000   
9                     0.0               3               738.000000   

   BounceRates  ExitRates  PageValues  SpecialDay  Month  OperatingSystems  \
0     0.200000   0.200000         0.0         0.0      1                 1   
1     0.000000   0.100000         0.0         0.0      1                 2   
2     0.200000   0.200000         0.0         0.0      1                 4   
3     0.050000   0.140000         0.0         0.0      1                 3   
4     0.020000   0.050000         0.0         0.0      1                 3   
5     0.015789   0.024561         0.0         0.0      1                 2   
6     0.200000   0.200000         0.0         0.4      1                 2   
7     0.200000   0.200000         0.0         0.0      1                 1   
8     0.000000   0.100000         0.0         0.8      1                 2   
9     0.000000   0.022222         0.0         0.4      1                 2   

   Browser  Region  TrafficType VisitorType  Weekend  Revenue  
0        1       1            1           1        0        0  
1        2       1            2           1        0        0  
2        1       9            3           1        0        0  
3        2       2            4           1        0        0  
4        3       1            4           1        1        0  
5        2       1            3           1        0        0  
6        4       3            3           1        0        0  
7        2       1            5           1        1        0  
8        2       2            3           1        0        0  
9        4       1            2           1        0        0

In [24]:
ds['Administrative']=(ds['Administrative']-ds['Administrative'].mean())/(ds['Administrative'].std())
ds['Administrative_Duration']=(ds['Administrative_Duration']-ds['Administrative_Duration'].mean())/(ds['Administrative_Duration'].std())
ds['Informational_Duration']=(ds['Informational_Duration']-ds['Informational_Duration'].mean())/(ds['Informational_Duration'].std())
ds['ProductRelated']=(ds['ProductRelated']-ds['ProductRelated'].mean())/(ds['ProductRelated'].std())
ds['ProductRelated_Duration']=(ds['ProductRelated_Duration']-ds['ProductRelated_Duration'].mean())/(ds['ProductRelated_Duration'].std())
ds['PageValues']=(ds['PageValues']-ds['PageValues'].mean())/(ds['PageValues'].std())

In [25]:
ds.head(10)

Administrative  Administrative_Duration  Informational  \
0       -0.696965                -0.457173              0   
1       -0.696965                -0.457173              0   
2       -0.696965                -0.457173              0   
3       -0.696965                -0.457173              0   
4       -0.696965                -0.457173              0   
5       -0.696965                -0.457173              0   
6       -0.696965                -0.457173              0   
7       -0.395922                -0.457173              0   
8       -0.696965                -0.457173              0   
9       -0.696965                -0.457173              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0               -0.244921       -0.690975                -0.624322   
1               -0.244921       -0.668491                -0.590879   
2               -0.244921       -0.690975                -0.624322   
3               -0.244921       -0.668491                -0.622929   
4               -0.244921       -0.488617                -0.296418   
5               -0.244921       -0.286258                -0.543735   
6               -0.244921       -0.690975                -0.624322   
7               -0.244921       -0.713459                -0.624322   
8               -0.244921       -0.668491                -0.604988   
9               -0.244921       -0.646007                -0.238676   

   BounceRates  ExitRates  PageValues  SpecialDay  Month  OperatingSystems  \
0     0.200000   0.200000   -0.317165         0.0      1                 1   
1     0.000000   0.100000   -0.317165         0.0      1                 2   
2     0.200000   0.200000   -0.317165         0.0      1                 4   
3     0.050000   0.140000   -0.317165         0.0      1                 3   
4     0.020000   0.050000   -0.317165         0.0      1                 3   
5     0.015789   0.024561   -0.317165         0.0      1                 2   
6     0.200000   0.200000   -0.317165         0.4      1                 2   
7     0.200000   0.200000   -0.317165         0.0      1                 1   
8     0.000000   0.100000   -0.317165         0.8      1                 2   
9     0.000000   0.022222   -0.317165         0.4      1                 2   

   Browser  Region  TrafficType VisitorType  Weekend  Revenue  
0        1       1            1           1        0        0  
1        2       1            2           1        0        0  
2        1       9            3           1        0        0  
3        2       2            4           1        0        0  
4        3       1            4           1        1        0  
5        2       1            3           1        0        0  
6        4       3            3           1        0        0  
7        2       1            5           1        1        0  
8        2       2            3           1        0        0  
9        4       1            2           1        0        0

In [26]:
X = np.array([ds['Administrative'],ds['Administrative_Duration'],ds['Informational'],ds['Informational_Duration'],ds['ProductRelated'],ds['ProductRelated_Duration'],ds['BounceRates'],ds['ExitRates'],ds['PageValues'],ds['SpecialDay'],ds['Month'],ds['OperatingSystems'],ds['Browser'],ds['Region'],ds['TrafficType'],ds['VisitorType'],ds['Weekend'],ds['Revenue']])
print(X.shape,X.T)


(18, 12330) [[-0.696964699439832 -0.45717286219939063 0 ... '1' 0 0]
 [-0.696964699439832 -0.45717286219939063 0 ... '1' 0 0]
 [-0.696964699439832 -0.45717286219939063 0 ... '1' 0 0]
 ...
 [-0.696964699439832 -0.45717286219939063 0 ... '1' 1 0]
 [0.5072074779711018 -0.032914582625706214 0 ... '1' 0 0]
 [-0.696964699439832 -0.45717286219939063 0 ... '0' 1 0]]


In [27]:
print(np.shape(X))
print(X)
X = X.T
print(np.matrix(X))


(18, 12330)
[[-0.696964699439832 -0.696964699439832 -0.696964699439832 ...
  -0.696964699439832 0.5072074779711018 -0.696964699439832]
 [-0.45717286219939063 -0.45717286219939063 -0.45717286219939063 ...
  -0.45717286219939063 -0.032914582625706214 -0.45717286219939063]
 [0 0 0 ... 0 0 0]
 ...
 ['1' '1' '1' ... '1' '1' '0']
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]]
[[-0.696964699439832 -0.45717286219939063 0 ... '1' 0 0]
 [-0.696964699439832 -0.45717286219939063 0 ... '1' 0 0]
 [-0.696964699439832 -0.45717286219939063 0 ... '1' 0 0]
 ...
 [-0.696964699439832 -0.45717286219939063 0 ... '1' 1 0]
 [0.5072074779711018 -0.032914582625706214 0 ... '1' 0 0]
 [-0.696964699439832 -0.45717286219939063 0 ... '0' 1 0]]


In [28]:
def computeDistance(x1,x2):
    d=np.sqrt(np.sum(np.power((x1-x2),2)))
    return d

In [29]:
print(computeDistance(X[0,:],X[1,:]))

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [11]:
def randomInit(X,no_of_clusters,no_of_samples,nof):
    centroids = []
    for i in range(no_of_clusters):
        temp = np.random.randint(0,no_of_samples)
        tempcents = []
        for j in range(nof):
            tempcents.append(X[temp,j])
        centroids.append(tempcents)
    centroids = np.matrix(centroids)
    return centroids

In [12]:
def labelling(x,centroids):
    distances = {}
    for i in range(len(centroids)):
        distances[computeDistance(x,centroids[i,:])] = i    
    return distances[min(distances.keys())]

In [13]:
def clusterAssignment(X,clusters,centroids):
    '''X : Data matrix
       clusters : A numpy array of size no_of_samples
       centroids : A numpy array of size no_of_clusters'''
    print(len(X))
    for i in range(len(X)):
        clusters[i] = labelling(X[i,:],centroids)
    return clusters


In [14]:
def updateCentroid(X,clusters,centroids,nof):
    sums = np.matrix(np.zeros(centroids.shape))
    count = np.zeros(len(centroids),dtype=int)
    newCentroids = np.matrix(np.zeros(centroids.shape))
    for i in range(len(X)):
        for j in range(nof):
            sums[clusters[i],j]+=X[i,j]
        count[clusters[i]]+=1
    for i in range(len(centroids)):
        newCentroids[i,:] = sums[i,:]/count[i]
    return newCentroids

In [15]:
def kmeans_call(X,clusters,centroids,iterations,nof):
    for i in range(iterations):
        clusters = clusterAssignment(X,clusters,centroids)
        new_centroids = updateCentroid(X,clusters,centroids,nof)     
        centroids = new_centroids
        #plotClusters(centroids,clusters,X)
    return centroids,clusters

In [16]:
number_of_samples = 12330
number_of_clusters = 2
number_of_iterations = 1000
number_of_features = 18

In [17]:
centroids = randomInit(X,number_of_clusters,number_of_samples,number_of_features)

In [18]:
clusters = np.zeros(len(X))

In [19]:
(finalCentroids,finalClusters) = kmeans_call(X,clusters,centroids,number_of_iterations,number_of_features)

12330


TypeError: unsupported operand type(s) for -: 'float' and 'str'

In [121]:
d=np.array([[1,2],[3,4]])
print(d.T)


[[1 3]
 [2 4]]
